language: generic
dist: trusty

services: 
  - docker

before_install: 
  - sudo apt-get install dc
  # prime the cache by fetching the latest release of all images
  - ls teradatalabs/ | awk '{print "teradatalabs/" $0 }' | xargs -L1 time docker pull || true

install: make

